version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/AsyrafHussin/wa-gateway-go
